package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dbeckwith
 */
public class AllGamesViewPanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = -6990619499118841478L;

    /**
     * Creates new form GameViewPanel
     */
    public AllGamesViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        requirementsPanel = new edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.RequirementsPanel();
        detailOrVotePanel = new javax.swing.JPanel();
        votePanel = new edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.VotePanel();
        detailPanel = new edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.DetailPanel();
        gamesListPanel1 = new edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.GamesListPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setTopComponent(requirementsPanel);

        detailOrVotePanel.setLayout(new java.awt.CardLayout());
        detailOrVotePanel.add(votePanel, "card1");
        detailOrVotePanel.add(detailPanel, "card2");

        jSplitPane1.setRightComponent(detailOrVotePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamesListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gamesListPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailOrVotePanel;
    private edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.DetailPanel detailPanel;
    private edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.GamesListPanel gamesListPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.RequirementsPanel requirementsPanel;
    private edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main.VotePanel votePanel;
    // End of variables declaration//GEN-END:variables
}
