package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author Sonaxaton
 */
public class AllGamesViewPanel extends javax.swing.JPanel {
    
    /**
     *
     */
    private static final long serialVersionUID = -6990619499118841478L;
    
    /**
     * Creates new form GameViewPanel
     */
    public AllGamesViewPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        SummaryTablePanel = new javax.swing.JPanel();
        DetailPanel = new javax.swing.JPanel();
        RequirementPanel = new javax.swing.JPanel();
        GameInteractionPanel = new javax.swing.JPanel();
        
        SummaryTablePanel.setBorder(javax.swing.BorderFactory
                .createEtchedBorder());
        
        javax.swing.GroupLayout SummaryTablePanelLayout = new javax.swing.GroupLayout(
                SummaryTablePanel);
        SummaryTablePanel.setLayout(SummaryTablePanelLayout);
        SummaryTablePanelLayout.setHorizontalGroup(SummaryTablePanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 204, Short.MAX_VALUE));
        SummaryTablePanelLayout.setVerticalGroup(SummaryTablePanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));
        
        DetailPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        RequirementPanel.setBorder(javax.swing.BorderFactory
                .createTitledBorder("Requirement"));
        
        javax.swing.GroupLayout RequirementPanelLayout = new javax.swing.GroupLayout(
                RequirementPanel);
        RequirementPanel.setLayout(RequirementPanelLayout);
        RequirementPanelLayout.setHorizontalGroup(RequirementPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 375, Short.MAX_VALUE));
        RequirementPanelLayout.setVerticalGroup(RequirementPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 127, Short.MAX_VALUE));
        
        GameInteractionPanel.setBorder(javax.swing.BorderFactory
                .createEtchedBorder());
        GameInteractionPanel.setLayout(new java.awt.CardLayout());
        
        javax.swing.GroupLayout DetailPanelLayout = new javax.swing.GroupLayout(
                DetailPanel);
        DetailPanel.setLayout(DetailPanelLayout);
        DetailPanelLayout
                .setHorizontalGroup(DetailPanelLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                DetailPanelLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                DetailPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(
                                                                GameInteractionPanel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                RequirementPanel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))
                                        .addContainerGap()));
        DetailPanelLayout
                .setVerticalGroup(DetailPanelLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                DetailPanelLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(
                                                RequirementPanel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                GameInteractionPanel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                233, Short.MAX_VALUE)
                                        .addContainerGap()));
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SummaryTablePanel,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DetailPanel,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(
                                                        DetailPanel,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addComponent(
                                                        SummaryTablePanel,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailPanel;
    private javax.swing.JPanel GameInteractionPanel;
    private javax.swing.JPanel RequirementPanel;
    private javax.swing.JPanel SummaryTablePanel;
    // End of variables declaration//GEN-END:variables
}
