/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

/**
 *
 * @author nfbrown
 */
public class VotePanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 6053116033835102214L;

    /**
     * Creates new form VotePanel
     */
    public VotePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estimateLabel = new javax.swing.JLabel();
        voteField = new javax.swing.JLabel();
        completedVotesField = new javax.swing.JLabel();
        endsLabel = new javax.swing.JLabel();
        endTimeField = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        estimateSelectionBox = new javax.swing.JComboBox<Float>();
        votesProgressBar = new javax.swing.JProgressBar();

        estimateLabel.setText("Estimate:");

        voteField.setText("Votes:");

        completedVotesField.setText("0/15");

        endsLabel.setText("Ends at:");

        endTimeField.setText("3/23 6:00 PM");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        estimateSelectionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1", "2", "3", "10", "20", "50", "100" }));
        estimateSelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimateSelectionBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estimateLabel)
                        .addGap(10, 10, 10)
                        .addComponent(estimateSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voteField)
                        .addGap(18, 18, 18)
                        .addComponent(votesProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completedVotesField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endTimeField)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimateLabel)
                    .addComponent(submitButton)
                    .addComponent(estimateSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(voteField)
                        .addComponent(completedVotesField))
                    .addComponent(votesProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endsLabel)
                    .addComponent(endTimeField))
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_submitButtonActionPerformed

    private void estimateSelectionBoxActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estimateSelectionBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_estimateSelectionBoxActionPerformed

    private void estimateFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_estimateFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_estimateFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completedVotesField;
    private javax.swing.JLabel endTimeField;
    private javax.swing.JLabel endsLabel;
    private javax.swing.JLabel estimateLabel;
    private javax.swing.JComboBox<Float> estimateSelectionBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel voteField;
    private javax.swing.JProgressBar votesProgressBar;
    // End of variables declaration//GEN-END:variables
}
